### ISSUE TITLE
Version for Godot 4.2.1

### ISSUE THREAD

**Issue by deezaster** [LettucePie/ios-plugin-integrate-demo#4]
Is it possible to create a compilation for the stable Godot version 4.2.1?

I have tried it. I was able to successfully create the compilation for all 3 schemas (debug,release and debug_release). But unfortunately the export from Godot does not work.

```
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** ARCHIVE FAILED **


The following build commands failed:
	Ld /Users/andy/Library/Developer/Xcode/DerivedData/jumpermobile-ezjvmnupqovbkkcdcyxtqxyomcvj/Build/Intermediates.noindex/ArchiveIntermediates/jumpermobile/InstallationBuildProductsLocation/Applications/jumpermobile.app/jumpermobile normal (in target 'jumpermobile' from project 'jumpermobile')
(1 failure)
```

**Comment by LettucePie** [comment]
Hello

It will be impossible for me to test this, I have abandoned apple development and no longer have any apple hardware.

In the past, I encountered this error when I was trying to load in plugins that mismatched the version of Godot. So for example if you `git checkout` to 4.1.2 instead of 4.2.1, compile, then run the build scripts, it will fail. So first I would double check what Godot version you're compiling from. You can try this with `git log`.

You may also find help in this issue post here https://github.com/godotengine/godot-ios-plugins/issues/47

**Comment by deezaster** [comment]
I understand. Thank you for the hint.

**Comment by deezaster** [comment]
That was actually the problem. Now everything works as it should.
